version: '3.4'

services:
  publicapi:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_Kestrel__Certificates__Default__Password=@root#098@
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/root/.aspnet/https/publicapi.pfx
    ports:
      - "5200:443"
      - "5201:80"
    volumes:
      - "./.aspnet/https:/root/.aspnet/https:ro"
      - "./.aspnet/DataProtection-Keys:/root/.aspnet/DataProtection-Keys:ro"
